apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: git-ssh-key
  annotations:
    "helm.sh/hook": pre-install
spec:
  backendType: gcpSecretsManager
  projectId: {{ .Values.projectId }}
  data:
    - key: git-ssh-key
      name: id_rsa
      version: latest