replicas: 1

rollingUpdate:
  maxSurge: 50%
  maxUnavailable: 25%

imagePullPolicy: Always

# Deploy a different image to the intended release (useful for test and development)
imageOverride:
  enabled: true
  repo: eu.gcr.io/sbat-gcr-release/securebanking/spring-config-server
  tag: latest

server:
  port: 8888

git:
  org: SecureBankingAcceleratorToolkit
  repo: securebanking-openbanking-spring-config
  branch: master

resources: {}