name: merge-master

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md

env:
  SERVICE_NAME: securebanking-spring-config-server

jobs:
  test:
    runs-on: ubuntu-latest
    name: Check master integrity
    outputs:
      isUpdatedChart: ${{ steps.validator.outputs.isUpdatedChart }}
      gcrRepo: ${{ steps.repository.outputs.gcrRepo }}
      helmRepo: ${{ steps.repository.outputs.helmRepo }}
      version: ${{ steps.binary.outputs.version }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: "14"
          architecture: x64

      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven2-${{ hashFiles('**/pom.xml') }}

      - name: test
        run: |
          make verify

      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCR_KEY }}
          export_default_credentials: true

      - name: binary version
        id: binary
        run: |
          BINARY_VERSION=$(make version)
          echo ::set-output name=version::"$BINARY_VERSION"

      - run: |
          gcloud auth configure-docker

      - name: Check for compatible release
        id: validator
        uses: SecureBankingAccessToolkit/securebanking-version-validator@master
        with:
          binaryVersion: ${{ steps.binary.outputs.version }}
          chartPath: "_infra/helm/${{ env.SERVICE_NAME }}/Chart.yaml"
      
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_ACCESS_TOKEN }}

      - name: set Repository variables
        id: repository
        run:
          if [[ "${{ steps.validator.outputs.isRelease }}" == "true" ]] then
            echo "setting releases repositories"
            echo ::set-output name=gcrRepo::"${{ secrets.RELEASE_REPO }}"
            echo ::set-output name=helmRepo::"${{ secrets.HELM_RELEASE_BUCKET }}"
          else
            echo "setting develop repositories"
            echo ::set-output name=gcrRepo::"sbat-gcr-develop"
            echo ::set-output name=helmRepo::"${{ secrets.HELM_DEV_BUCKET }}"
          fi
  
  update:
    runs-on: ubuntu-latest
    name: Update helm chart
    needs: [test]
    if: ${{ needs.test.outputs.isUpdatedChart == 'true' }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_BOT_TOKEN }}

      - name: Commit version update
        run: |
          git config --local user.email "fropenbanking@users.noreply.github.com"
          git config --local user.name "fropenbanking"
          git add _infra/helm/${{ env.SERVICE_NAME }}/Chart.yaml
          git commit --allow-empty -m "Bumping Chart versions ${{ steps.binary.outputs.version }}"
      - name: Temporarily disable "include administrators" protection
        uses: benjefferies/branch-protection-bot@master
        with:
          access-token: ${{ secrets.GH_BOT_TOKEN }}
          enforce_admins: false
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_BOT_TOKEN }}
          branch: master
      - name: Enable "include administrators" branch protection
        uses: benjefferies/branch-protection-bot@master
        if: always()
        with:
          access-token: ${{ secrets.GH_BOT_TOKEN }}
          enforce_admins: true
  
  package:
    runs-on: ubuntu-latest
    name: package artifacts
    needs: [test]
    if: ${{ needs.test.outputs.isUpdatedChart == 'false' }}
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          make docker repo=${{ needs.test.outputs.gcrRepo }}

      - name: package helm
        run: |
          make helm version=${{ needs.test.outputs.version }}

      - name: Publish Release Chart 
        id: upload
        uses: google-github-actions/upload-cloud-storage@main
        with:
          path: ${{ env.SERVICE_NAME }}-${{ needs.test.outputs.version }}.tgz
          destination: ${{ needs.test.outputs.helmRepo }}/${{ env.SERVICE_NAME }}
