name: pull-request

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - README.md

env:
  HELM_DIRECTORY: _infra/helm/
  SERVICE_NAME: securebanking-spring-config-server

jobs:
  build:
    runs-on: ubuntu-latest
    name: Check PR integrity
    steps:
      - uses: actions/checkout@v2

      - name: binary version
        id: binary
        run: |
          BINARY_VERSION=$(make version)
          echo ::set-output name=version::"$BINARY_VERSION"

      - name: Check for compatible release
        id: validator
        uses: SecureBankingAccessToolkit/securebanking-version-validator@master
        with:
          binaryVersion: ${{ steps.binary.outputs.version }}
          chartPath: "_infra/helm/${{ env.SERVICE_NAME }}/Chart.yaml"
      
      - name: Commit ob-deploy version update
        working-directory: ./${{ env.SERVICE_NAME }}
        run: |
          git config --global user.email "fropenbanking@users.noreply.github.com"
          git config --global user.name "fropenbanking"
          git add _infra/helm/${{ env.SERVICE_NAME }}/Chart.yaml
          git commit --allow-empty -m "Bumping version ${{ steps.binary.outputs.version }}"

      - name: Temporarily disable "include administrators" protection
        if: ${{ steps.validator.outputs.isUpdatedChart == 'true' }}
        uses: benjefferies/branch-protection-bot@master
        with:
          access-token: ${{ secrets.GH_BOT_TOKEN }}
          enforce_admins: false
      