name: pull-request

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - README.md

env:
  HELM_DIRECTORY: _infra/helm/
  SERVICE_NAME: securebanking-spring-config-server

jobs:
  build:
    runs-on: ubuntu-latest
    name: Check PR integrity
    steps:
      - uses: actions/checkout@v2

      - name: Check for compatible release
        id: validator
        uses: SecureBankingAccessToolkit/securebanking-version-validator@master
        with:
          binaryVersion: ${{ steps.binary.outputs.version }}
          chartPath: "_infra/helm/${{ env.SERVICE_NAME }}/Chart.yaml"
      
      - name: echo isRelease
        run: |
          echo ${{ steps.validator.outputs.isRelease }}
          echo ${{ steps.validator.outputs.isUpdatedChart }}
      
      - name: Temporarily disable "include administrators" protection
        if: ${{ steps.validator.outputs.isUpdatedChart == 'true' }}
        uses: benjefferies/branch-protection-bot@master
        with:
          access-token: ${{ secrets.GH_BOT_TOKEN }}
          enforce_admins: false
      