name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
      
      - name: helm version
        id: helm
        run: |
          HELM_VERSION=$(make version)
          echo ::set-output name=version::"$HELM_VERSION"

      - name: package helm
        run: |
          make helm version=${{ steps.helm.outputs.version }}

      - name: Publish Release Chart 
        id: upload
        uses: google-github-actions/upload-cloud-storage@v0
        with:
          path: ${{ env.SERVICE_NAME }}-${{ steps.helm.outputs.version }}.tgz
          destination: ${{ secrets.HELM_RELEASE_BUCKET }}/${{ env.SERVICE_NAME }}
      
      - name: Release Docker Image
        run: |
          make docker tag=${{ github.event.release.tag_name }} gcr-repo=${{ secrets.RELEASE_REPO }}
